export type PortfolioTier = 1 | 2 | 3;

export interface PortfolioProject {
  id: string;
  name: string;
  categoryLabel: string;
  categoryKey: string;
  summary: string;
  capabilities: string[];
  image: string;
  imageAlt: string;
  imageFit?: "cover" | "contain";
  detailHref: string;
  liveUrl?: string;
  tier: PortfolioTier;
  layoutSpan?: "flagship" | "large" | "standard";
  imageShape?: "default" | "arch" | "offset";
}

export const portfolioCategories = [
  { id: "all", label: "ALL" },
  { id: "enterprise-ai", label: "ENTERPRISE AI" },
  { id: "data", label: "DATA" },
  { id: "healthcare", label: "HEALTHCARE" },
  { id: "talent", label: "TALENT" },
  { id: "commerce", label: "COMMERCE" },
  { id: "business-apps", label: "BUSINESS APPLICATIONS" },
] as const;

export const portfolioProjects: PortfolioProject[] = [
  {
    id: "data-agent",
    name: "Data Agent",
    categoryLabel: "ENTERPRISE AI",
    categoryKey: "enterprise-ai",
    summary: "Document intelligence for contracts, clauses, and repository analysis.",
    capabilities: ["Clause extraction", "Source verification", "Repository search"],
    image: "/innovation/data-agent-hero.png",
    imageAlt: "Data Agent document extraction and contract intelligence interface",
    imageFit: "cover",
    detailHref: "/work/innovation/data-agent",
    liveUrl: "https://data-agent-ca.vercel.app",
    tier: 1,
    layoutSpan: "flagship",
  },
  {
    id: "mediguide",
    name: "MediGuide AI",
    categoryLabel: "HEALTHCARE AI",
    categoryKey: "healthcare",
    summary: "Clinical assistant for lab results, timelines, and care documentation.",
    capabilities: ["Lab interpretation", "Care timelines", "Document Q&A"],
    image: "/innovation/mediguide-hero.png",
    imageAlt: "MediGuide AI healthcare document and lab assistant interface",
    imageFit: "cover",
    detailHref: "/work/innovation/mediguide-ai",
    liveUrl: "https://mediguide-ai-woad.vercel.app",
    tier: 2,
    layoutSpan: "large",
  },
  {
    id: "joblens",
    name: "JobLens",
    categoryLabel: "CAREER TECHNOLOGY",
    categoryKey: "talent",
    summary: "Resume analysis, ATS feedback, and job matching in one workspace.",
    capabilities: ["Resume scoring", "ATS keywords", "Job matching"],
    image: "/innovation/joblens-hero.png",
    imageAlt: "JobLens resume analysis and job matching interface",
    imageFit: "cover",
    detailHref: "/work/innovation/joblens",
    liveUrl: "https://joblens-seven.vercel.app",
    tier: 2,
    layoutSpan: "large",
  },
  {
    id: "data-explorer",
    name: "Data Explorer",
    categoryLabel: "ENTERPRISE AI",
    categoryKey: "data",
    summary: "Search and compare documents across fields, dates, and obligations.",
    capabilities: ["Cross-doc search", "Schema export", "Audit traceability"],
    image: "/innovation/data-agent-platform.png",
    imageAlt: "Data Explorer repository and document aggregation interface",
    imageFit: "cover",
    detailHref: "/ai-data",
    liveUrl: "https://data-agent-ca.vercel.app/repository",
    tier: 2,
    layoutSpan: "large",
  },
  {
    id: "convera",
    name: "Convera",
    categoryLabel: "ENTERPRISE AI",
    categoryKey: "enterprise-ai",
    summary: "API gateway and message hub connecting ERP, CRM, and cloud systems.",
    capabilities: ["Schema validation", "Event routing", "ERP connectivity"],
    image: "/portfolio/convera.png",
    imageAlt: "Convera integration hub connecting enterprise systems",
    imageFit: "cover",
    detailHref: "/capabilities/digital-engineering",
    tier: 2,
    layoutSpan: "standard",
  },
  {
    id: "hr-talent",
    name: "HR & Talent",
    categoryLabel: "CAREER TECHNOLOGY",
    categoryKey: "talent",
    summary: "Workforce suite for recruiting, time, leave, and payroll workflows.",
    capabilities: ["Recruit-to-hire", "Self-service", "Payroll integration"],
    image: "/portfolio/hr-talent.png",
    imageAlt: "HR and Talent workforce management portal interface",
    imageFit: "cover",
    detailHref: "/work/innovation",
    tier: 2,
    layoutSpan: "standard",
  },
  {
    id: "importnest",
    name: "ImportNest AI Agent",
    categoryLabel: "AI COMMERCE",
    categoryKey: "commerce",
    summary: "AI shopping comparison with Total Known Cost across verified retailers.",
    capabilities: ["Product search", "Cost calculation", "Price alerts"],
    image: "/portfolio/importnest.png",
    imageAlt: "ImportNest AI shopping comparison and product search interface",
    imageFit: "cover",
    detailHref: "https://importnest.vercel.app",
    liveUrl: "https://importnest.vercel.app",
    tier: 3,
    layoutSpan: "standard",
  },
  {
    id: "smartwrite",
    name: "SmartWrite AI",
    categoryLabel: "CONTENT AI",
    categoryKey: "enterprise-ai",
    summary: "Writing assistant for grammar, rewriting, tone, and readability.",
    capabilities: ["Grammar check", "Tone rewrite", "Readability score"],
    image: "/portfolio/smartwrite.png",
    imageAlt: "SmartWrite AI writing editor and grammar analysis interface",
    imageFit: "cover",
    detailHref: "https://grammarly-app-seven.vercel.app",
    liveUrl: "https://grammarly-app-seven.vercel.app",
    tier: 3,
    layoutSpan: "standard",
  },
  {
    id: "bosiano",
    name: "Bosiano",
    categoryLabel: "E-COMMERCE",
    categoryKey: "commerce",
    summary: "Luxury fashion storefront with editorial catalog and mobile commerce.",
    capabilities: ["Product catalog", "Mobile commerce", "Brand storytelling"],
    image: "/portfolio/bosiano.png",
    imageAlt: "Bosiano luxury fashion e-commerce storefront",
    imageFit: "cover",
    detailHref: "https://bosiano.vercel.app",
    liveUrl: "https://bosiano.vercel.app",
    tier: 3,
    layoutSpan: "standard",
  },
  {
    id: "sarco-appliances",
    name: "Sarco Appliances",
    categoryLabel: "BUSINESS APPLICATIONS",
    categoryKey: "business-apps",
    summary: "Appliance sales, delivery, installation, and repair service platform.",
    capabilities: ["Service catalog", "Repair dispatch", "Delivery scheduling"],
    image: "/portfolio/sarco.png",
    imageAlt: "Sarco Appliances commercial service and product website",
    imageFit: "cover",
    detailHref: "https://sarco-appliances.vercel.app",
    liveUrl: "https://sarco-appliances.vercel.app",
    tier: 3,
    layoutSpan: "standard",
  },
  {
    id: "smart-appliances",
    name: "Smart Appliances",
    categoryLabel: "BUSINESS APPLICATIONS",
    categoryKey: "business-apps",
    summary: "HVAC and home-service booking with technician dispatch workflows.",
    capabilities: ["Service booking", "HVAC diagnostics", "Appointment confirm"],
    image: "/portfolio/smart-appliances.png",
    imageAlt: "Smart Appliances home service booking interface",
    imageFit: "cover",
    detailHref: "https://project-i8icw-ebon.vercel.app",
    liveUrl: "https://project-i8icw-ebon.vercel.app",
    tier: 3,
    layoutSpan: "standard",
  },
  {
    id: "appointease",
    name: "AppointEase",
    categoryLabel: "BUSINESS APPLICATIONS",
    categoryKey: "business-apps",
    summary: "Appointment scheduling with service, date, time, and customer intake.",
    capabilities: ["Calendar picker", "Service selection", "Booking confirm"],
    image: "/portfolio/appointease.png",
    imageAlt: "AppointEase appointment booking interface",
    imageFit: "cover",
    detailHref: "https://appointease-psi.vercel.app",
    liveUrl: "https://appointease-psi.vercel.app",
    tier: 3,
    layoutSpan: "standard",
  },
];
